export enum LoggerEvents {
    NEW_PAYMENT = 'NEW_PAYMENT',
    PAYMENT_ERROR = 'PAYMENT_ERROR',
    AGGREGATION_ERROR = 'AGGREGATION_ERROR',
    PROCESSING_ERROR = 'PROCESSING_ERROR',
    VALIDATING_ERROR = 'VALIDATING_ERROR',
    NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',
    REFUND_ERROR = 'REFUND_ERROR'
}
