name: Migrations

on:
  push:
    branches:
      - master

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Detect changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          migrations:
            - 'prisma/migrations/**'

  migrations:
    runs-on: ubuntu-latest
    needs: check-migrations
    if: ${{ needs.check-migrations.outputs.migrations == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install prisma@6.4.1

      - name: Apply migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
